version: "3"

services:
    nuke_nginx:
        container_name: nuke_nginx
        restart: always
        image: nginx:alpine
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/var/www/backend
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - nuke_php
        networks:
            - nuke

    nuke_php:
        container_name: nuke_app
        restart: always
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - "9000:9000"
        volumes:
            - ./backend:/var/www/backend
        networks:
            - nuke

    nuke_postgres:
        container_name: nuke_postgres
        image: postgres:14.2-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdb:/var/lib/postgresql/data
        networks:
            - nuke

volumes:
    pgdb: {}

networks:
    nuke: {}
