<?php


namespace App\Util;


use App\Entity\Account\Contact;
use App\Entity\Account\Tenant;
use App\Entity\Sales\Product;
use App\Entity\Sales\ProductCatalog;
use App\Entity\Sales\UnitOfMeasurement;
use Doctrine\ORM\EntityManagerInterface;

class Insert
{

    public $parfums = [
        ['name' => 'GIORGIO ARMANI ACQUA DI GIO MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'AVENTUS GREED S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'NASOMATTO BLACK AFGANO UNISEX S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'CARTIER LA PANTER S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHANEL EGOISTE PLATINIUM MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'DIMA BILAN EXCITE MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'NARCISO RODRIGUEZ FOR HER WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'NINA RICCI NINA S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'N-70 S', 'price' => '1.2', 'manufacturer' => '65'],
        ['name' => 'ZEM ZEM MIDNIGHT FANTASY S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LACOSTE FEMME S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LANCOME TRESOR MIDNIGHT ROSE WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LANCOME CLIMAT WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LACOSTE RED MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'KENZO L EAU PAR WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHRISTION DIOR JADORE S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'JAQLER MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'JASMIN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'ESCADA SEXY GRAFFITI WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'HUGO BOSS HUGO MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GREN TEA S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'FENDI S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'KILIAN WHITE CRYSTAL S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'LANCOME LANUIT TRESSOR WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LANCOME LAVIE EST BELLE S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LANVIN MERRY ME WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LACOSTE WHITE BLANC MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LANVIN ECLAT S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'PACO RABANNE LADY MILLION WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'MOSCHINO FUNNY S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'MONTALE BLACK AOUD UNISEX S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'MONTALE ROSES MUSK UNISEX S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'ESCENTRIC MOLECULES S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'VICTORIAS SECRET BOMBSHELL S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'VERSACE BRIGHT CRYSTAL WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'VERSACE BLACK WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'VERSACE FRAICHE MAN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'VERSACE VERSENSE WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'TIZIANA TERENZI KIRKE UNISEX S', 'price' => '1.2', 'manufacturer' => '65'],
        ['name' => 'TOM FORD TOBACCO VANILLE UNISEX S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'HERMES TERRE S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'TRUSSADI MY LAND S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'TOM FORD OUD WOOD UNISEX S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'AVON TODAY WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'TOM FORD BLACK ORCHID UNISEX S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'TRUSSARDI UOMO S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'DONNA TRUSSARDI WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LUCIA S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'SOSPIRO ERBA PURA UNISEX S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'SEHRIZAD S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'PACO RABANNE ONE MILLION MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'PACO RABANNE OLYMPEA WOMAN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'POLO BLUE MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'NARKOTIQE FLEUR UNISEX S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'PRADA CANDY WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'AMOUAGE INTERLUDE MEN S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'ARMANI BLACK CODE S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GIORGIA ARMANI SI WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'ANTONIO BANDERAS MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'ANGEL DEMON SECRET S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'ARMAND BASI IN RED WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CACHAREL AMOR AMOR WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'AQVA BVLGARI MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'AZZARO CHROME MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'BVLGARI JASMIN NOIRI S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'BLACK OPIUM WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'BURBERRY MY BURBERRY S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHANEL COCO WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHANEL COCO MADEMOISELLE WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHANEL CHANCE WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CALDION MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GUCCI GUILTY WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GUCCI GUILTY MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GUCCI FLORA WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GUCCI RUSH WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHANEL EAU TENDRE WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHANEL ALLURE SPORT MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHANEL BLUE DE CHANEL MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHRISTIAN DIOR SAUVAGE MEN S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'CHRISTIAN DIOR FAHRENHEIT MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GOOD GIRL WOMEN S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'C.H 212 CH WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'C.H 212 CH MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GIVENCHY PLAY MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CALVIN KLEIN EUPHORIA WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHLOE ROSES S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'ESCADA COLLECTION WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'YVES ROCHER EVIDENCE WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'EXPLORE S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'ECLAT SPORT S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'DUNHILL DESIRE S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'DUPONT WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'DAVIDOFF COOL WATER WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'D&G LIGHT BLUE WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'SOSPIRO ACCSENT S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'PACO RABANNE INVICTUS MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'VICTORIA SECRET BOMBSHEL', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BELLE DE OPIUM', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BLACK OPIUM', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'Y.S.L. MON PARIS', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'Y.S.L MANIFESTO', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'ISSEY MYAKE DISEY', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ZEM ZEM', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ZARA ORCHID WOMEN', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'ZARA TUBEROSE WOMEN', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'ZARA APPLE JOICE WOMEN', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'VERSACE VERSESCE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'VICTORIA SECRET STRAWBERRY CHAMPAGNE', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'VICTORIA SECRET HOT CRUSH', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'XERJOFF MORE THAN WORDS 15', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'XERJOFF MORE THAN WORDS 07', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'XERJOFF CASAMORATI MEFISTO K10', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'XERJOFF 40 KNOTS', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'VERSACE VERSUS', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'VERSACE EROS WOMEN', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'VERSACE EROS MAN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'VERSACE BLACK', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'VERSACE FRAICHE MAN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'VERSACE BRIGHT CRYSTAL', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'DONNA VALENTINO', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'JIMMY CHOO MAN ICE', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'MOSCHINO FUNNY', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'TODAY', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'TODAY TOMORROW', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'XERJOFF GRAN BALLO', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'VAN CLEEF MIDNIGHT IN PARIS', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'VAN CLEEF FEERIE', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'MISS JERY FRESH', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'FLORA BY GUCCI', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'TIZIANA TERENZI KIRKE K12', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'TIZIANA TERENZI KIRKE K8', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'TIZIANA TERENZI GUMIN', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'TIZIANA TERENZI CASSIOPEA UNISEX', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'TRUSSARDI UOMO', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'TRUSSADI MY LAND', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'TERRY MUGLER A MEN', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'DONNA TRUSSARDI', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'TOM FORD PORTAFINO', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'TOM FORD VELVET', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'TOM FORD NOIR DE NOIR', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'TOM FORD TABACCO VANEL', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'TOM FORD OUD VOOD', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'TOM FORD NOIR EXTREME', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'TOM FORD BLACK ORKID', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'TOM FORD WHITE PATCHOULI', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'OUD MALIKI', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'MUHAMMEDI', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'JAGLER', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'JASMIN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LANCOME HYPNOSE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LANCOME LAVIE EST BELLE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'MAGIE NOIR', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LANCOME TRESOR MIDNIGHT', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LANCOME CLIMAT', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LACOSTE ESSENTIAL', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LACOSTE WHITE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LACOSTE BLUE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LACOSTE GREEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LACOSTE EME', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LACOSTE RED', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BRITNY FANTAZY', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LUCIA', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'INCANTO SHINE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'SIGNORINA', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'SEHRIZAD', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'SHEYX 77 K6', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'SHEYX 70', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'SHEYX GOLD', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'SHEYX 77 K10', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'LOVELY', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'SHISEIDO ZEN', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'SOSPIRO ERBA PURA 05', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'SOSPIRO ERBA PURA 14', 'price' => '3.5', 'manufacturer' => '66'],
        ['name' => 'SASPIRO ERBA K-10', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'SOSPIRO ACCSENTO 05', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'SOSPIRO ACCSENTO 14', 'price' => '3.5', 'manufacturer' => '66'],
        ['name' => 'SOSPIRO ACCSENTO 08', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'SOSPIRO ENSENBLE', 'price' => '3.5', 'manufacturer' => '66'],
        ['name' => 'SOSPIRO OPERA', 'price' => '3.5', 'manufacturer' => '66'],
        ['name' => 'SILVER BOGART', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'ROJA ENIGMA', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'ROJA AMBER AOUD', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'ROBERTO CAVALI GOLD WOMEN', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'RICHARDO VERON k5', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'RICHARDO VERON k12', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'JOHAN SENSUAL', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'JAGUAR CLASSIC BLACK MEN', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'CIGAR', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'NEJMA 7', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'CANALI', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'HAYATI', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'COCAİNE', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'OPUS VIII', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'NARKOTIQUE GOLD', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'NARKOTIQUE CANAPLE', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'NARKOTIK VENUS', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'NARKOTIQUE FLEUR EX NIHILO', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'MOLECULE 01', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'MOLECULE 02 K5', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'MOLECULE 02 15', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'MOLECULE 02 10', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'MOLECULE 02 18', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'MOLECULE BEAUTIFUL 04 K15', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'ZARKO MOLECULE UNISEX 09', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'ESCENTRİC 01 K5', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'ESCENTRİC 02 K5', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'NARCISO RODRIGUEZ FOR HER', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'NARCISO RODRIGUEZ PINK', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'NINA RICCI', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'NARCISO RODRIGUEZ POUDRE K8', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'NARCISO RODRIGUEZ POUDRE JASMIN K6', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'MEMO ITALIAN LEATHER', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'MEMO AFRICAN LEATHER', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'MONTALE ROSES MUSK', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'MONTALE HONEY AOUD', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'MONTALE WHITE MUSK', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'MONTALE INTENSE CAFE', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'MONTALE BLACK AOUD', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'MONT BLANC LEGENT', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'MANCERA ROSES VANILLE', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'MANCERA AMBER ROSES', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'MANCERA VELVET VANILLA', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'KENZO', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'KENZO L EAUPAR WOMEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'KENZO FLOVER', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'KILIAN VODKA', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'KILIAN IMPERIAL TEA UNISEX', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'KILIAN WHITE CRYSTAL', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'KILIAN BAMBOO HARMONY', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'KILIAN LIAISONS DANGHEREUS (UNISEX)', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'KILIAN GOOD GRIL', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'KILIAN BLACK PHANTOM', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'FREDERIC MALLE PORTRAIT OF LADY', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'POLO BLUE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'PARCO PALLADIANO BOTEGA VENETA K5', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'POLO SPORT', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LADY MILLION', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'PACO RABANNE ONE MILLION', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'INVICTUS', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'PACO RABBANE OLYMPEA', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BACCARAT 540 ROUGE K15', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'BOND NO 9 NYC MANHATTAN UNISEX', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'C.H 212 VIP ROSES', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'C.H 212 SEXY MEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'C.H 212 WOMEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'C.H 212 MEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'C.H 212 VIP MEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'C.H GOOD GIRL', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'C.H 212 WIP CLUB', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'BYREDO BLACK SAFFRON UNISEX', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'BYREDO BIBLIOTHEQUE UNISEX', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'BYREDO AFRIQUE UNISEX', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'MY BURBERRY', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BURBERRY', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BVLGARI LEGEMME GYAN MEN', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'BVLGARI AQUA MARINE MEN', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'AQVA BVLGARI', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BVLGARI JASMIN NOIR', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BLACK AFGANO 15', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'BLACK AFGANO 20', 'price' => '5', 'manufacturer' => '66'],
        ['name' => 'BLACK AFGANO 05', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'BLACK AFGANO 10', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'NASOMATTO NUDIFLORUM UNISEX', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'NASOMATTO BARAONDA UNISEX', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'BOND 9 COOPER SQUARI', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'AVENTUS K15', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'AVENTUS GREED K5', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'AMOR-AMOR', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ANTONIO BANDERAS', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'AJMAL AMBER WOOD', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'CHROME AZZARO', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CHROME AZZARO PURE', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'ANNA SUI ANNA', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'ANNA SUI ROMANTICA', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'ANGEL DEMON LE SECRET', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ANNICK GOUTAL', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'L AMOUAGE LYRIC', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'ARMAND BASI IN RED', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ARMANI CODE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'AMUAJ INTERLUDE', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'AMOUAGE HONOUR MEN', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'GIORGIO ARMANI SI PASSIONE WOMEN', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'ARMANI ROSE ARABIE', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'DIOR JOY', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'GIORGIO ARMANI CEDRE POUR HOMME MEN', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'AMOUAGE MYTHS WOMEN', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'AMOUAGE DIA MAN', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'AMOUAGE REFLECTION', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'AL REHAB FARESH', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'AL REHAB SOFT', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'AL REHAB SULTAN', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'AL REHAB SECRET MEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'AL REHAB DALAL', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'AL REHAB SANDOS', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'COCO MILK', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CHOCOLAT K3', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'CARTIER LA PANTER K3', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'CARTIER LA PANTHERE 06', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'CARTIER DECLARATION MEN K3', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'CARTIER DECLARATION K6', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'CAPTAIN BLACK', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'CALDION', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'PRADA CANDY', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CHANEL CHANCE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CHANEL EGOISTE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CHANEL DE BLEU', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CHANEL TENDRE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CHANEL FRESH', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'CHANEL 5', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'COCO MADEMOISELLE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'COCO CHANEL', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CHANEL ALLURE SPORT', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CHANEL VIVE', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'CHANEL GABRIELLE', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'CHLOE DE ROSES', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CHLOE NOMADE WOMEN', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'CHLOE EUA DE PARFUM', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'FAHRENHEIT', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CRISTIAN DIOR ROSSE ELIXIR', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'CRISTIANO RONALDO LEGACY', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'JADORE (L)', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'D&G VELVET ROSE', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'D&G L"IMPERATIRCE', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'D&G THE ONE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'D&G LIGHT BLUE WOMEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CACHAREL YES IAM', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'CLIVE CRISTIAN GOLD №01', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'DIOR SAUVAGE 05', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'CHRISTIAN DIOR GRIS MONTAIGNE', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'MISS DIOR CRISTIAN', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'DAVIDOFF COOL WATER', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'DAVIDOFF CHAMPION', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'DESIRE BLUE', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'DUNHIL DESIRE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'DKNY NEW YORKE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'DIOR POISON', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'DUPONT WOMEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'DUPONT MEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'GIVENCHY PLAY', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ELIZABETH ARDEN GREEN TEA', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'GVENCHY POUR HOMME', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'IDEAL HOME GUERLAIN', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'ZARA GOLD FEMME WOMEN', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'INITIO PARFUMS MAGNETIC BLEND 8 UNISEX', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'INITIO/P PRIVES ABSOLUTE APHRODISIAC UNISEX', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'INITIO/P PRIVES BLESSED BARAKA UNISEX', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'INITIO/P PRIVES ADDICTIVE VIBRATION WOMEN', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'DIMA BILAN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'HEREM AKSA', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'HUGO BOSS BOTLET', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'L BALDARSARINO AMBRE', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'HUGO BOSS WOMEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'HUGO BOSS NUIT POUR FEMME', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'HUGO BOSS', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'HUGO BOSS - 98', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'HUGO BOSS BOTLED TONIC', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'CENNETUL FIRDEVS', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'MISS DIOR BLOOMBING', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'ARMANI PRIVE MOJESTIC', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'SI ARMANI', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ARMANI ACQUA DIGIO', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'GREED VIKING', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'GREED GREEN IRISH TVEED MEN', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'HERMES NARGULE', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'HERMES TERRE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'GUCCI BAMBOO', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'GUCCI ENVY ME', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'GUCCI GUILTY WOMEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'GUCCI GUILTY MEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'GUCCI DE PARFUM', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'GUCCI RUSH', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'GUCCI RUSH 2', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BLUE RUSH', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'ASKI MEMNU', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'FIDJI', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => '7 MEYVE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'FATIME', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'FENDI', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'C.C EUPHORIA', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CALVIN KLEIN ETERNETY', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'M 008 (HEREM MESED)', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'ECLAT LANVIN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ECLAT SPORT', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'MISTER DYNASTY OF MONACO', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'EVIDENCE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ESCADA MAGNETISIM', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ESCADA TROPİCAL', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ESCADA GRAFITTY', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ELIE SAAB', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'EISENBERG JOSE', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'EISENBERG DIABOLUGUE', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'EXPLORE 03', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'N-70', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'DIOR SAUVAGE 12', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'IDYLLE GUERLAIN', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'AJMAL GAFIE', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'SOSPIRO ERBA PURA K20', 'price' => '5', 'manufacturer' => '66'],
        ['name' => 'LANVIN MERRY ME', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'C.H BAD BOY K5', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'MONTALE VANILLA EXTASY', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'ALEXSANDR J', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'D&G BY K FOR MEN', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'EMPORIO ARMANI STRONGER WITH YOU', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'VICTORIA SECRET CRAVING', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'XERJOFF MORE THAN WORDS K20', 'price' => '5', 'manufacturer' => '66'],
        ['name' => 'LACOSTE FEMME', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'PEGASUS PARFUM DE MARLY', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'AMOUAGE NOIR', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'EME MENTOL', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'ENCR NOIRE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'INCANTO BLOMM (G)', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'FOR MEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'JENIFER LOPES STILL', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'VICTORIA SECRET AMBER ROMANCE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'EME GOLD', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'ARMANI CODE KASMIR', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'OUD', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'MONTALE CHOC0LAT', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'ALEX MORNING MUSK', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'AMOR EGZOTIK (G)', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BVLGARI AU THE NOIR K6', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'TABAK', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BRIONI', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'LACOSTE MAGNETIC FOR HER', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'LACOSTE MAGNETIC FOR HIM', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'MANCERA INTENSIVE GOLD', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'ROBERTO CAVALLI DIVINE OUD', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'ROJA DANGER', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'ROJA EYSIUM', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'ROJA SCANDAL', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'GREED SILVER MOUNTAIN', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'RASASI ROYAL', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'COBRA', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'AJMAL 1001 NIGHTS', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'ROJA OLIGARCH 2016)', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'MEGAMARE', 'price' => '0', 'manufacturer' => '66'],
        ['name' => 'BLACK AFGANO IN KRAL', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'NARKOTIQE FLEUR UNISEX S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'LANVIN MERRY ME WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'PACO RABANNE INVICTUS MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GUCCI FLORA WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'SOSPIRO ERBA PURA UNISEX S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'GUCCI GUILTY MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'HUGO BOSS HUGO MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'ARMANI BLACK CODE S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'DONNA TRUSSARDI WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHANEL COCO MADEMOISELLE WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'ANTONIO BANDERAS MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'HERMES TERRE S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LANCOME LAVIE EST BELLE S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GUCCI RUSH WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHRISTIAN DIOR SAUVAGE MEN S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'FENDI S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'VERSACE VERSENSE WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHANEL CHANCE WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CHANEL EAU TENDRE WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'VERSACE BLACK WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LACOSTE RED MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'CALDION MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'DIMA BILAN EXCITE MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'JASMIN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'N-70 S', 'price' => '1.2', 'manufacturer' => '65'],
        ['name' => 'CHRISTION DIOR JADORE S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'BLACK OPIUM WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LUCIA S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'BURBERRY MY BURBERRY S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'TOM FORD BLACK ORCHID UNISEX S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LACOSTE FEMME S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GOOD GIRL WOMEN S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'CHRISTIAN DIOR FAHRENHEIT MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'C.H 212 CH MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'DUNHILL DESIRE S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'ESCENTRIC MOLECULES S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'CHANEL ALLURE SPORT MEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'GIORGIA ARMANI SI WOMEN S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'LANVIN ECLAT S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'BVLGARI JASMIN NOIRI S', 'price' => '0.5', 'manufacturer' => '65'],
        ['name' => 'AVENTUS GREED S', 'price' => '0.7', 'manufacturer' => '65'],
        ['name' => 'LANCOME TRESOR MIDNIGHT', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'C.C EUPHORIA', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'DUPONT WOMEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'OUD', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'DIOR POISON', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BVLGARI AU THE NOIR K6', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'GUCCI BAMBOO', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'SOSPIRO ENSENBLE', 'price' => '3.5', 'manufacturer' => '66'],
        ['name' => 'ENCR NOIRE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LANCOME CLIMAT', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ALEX MORNING MUSK', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'LACOSTE MAGNETIC FOR HER', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'LANVIN MERRY ME', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'LACOSTE FEMME', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'CHANEL CHANCE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'EME GOLD', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'TABAK', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'DUPONT MEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'MONTALE AOUD FOREST (UNISEX', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'PEGASUS PARFUM DE MARLY', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'D&G VELVET ROSE', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'FOR MEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'JAGLER', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'MOLECULE 01', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'MUHAMMEDI', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'GUCCI ENVY ME', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'GREED VIKING', 'price' => '4', 'manufacturer' => '66'],
        ['name' => 'VICTORIA SECRET AMBER ROMANCE', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'GUCCI RUSH 2', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'EME MENTOL', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'JENIFER LOPES STILL', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'RICHARDO VERON k12', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'DESIRE BLUE', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'GUCCI GUILTY WOMEN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'ARMANI ROSE ARABIE', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'CANALI', 'price' => '2.5', 'manufacturer' => '66'],
        ['name' => 'VERSACE EROS MAN', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'MONTALE WHITE AUD', 'price' => '1.5', 'manufacturer' => '66'],
        ['name' => 'CAPTAIN BLACK', 'price' => '0.7', 'manufacturer' => '66'],
        ['name' => 'MEMO ITALIAN LEATHER', 'price' => '2', 'manufacturer' => '66'],
        ['name' => 'TOM FORD TABACCO VANEL', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'C.H GOOD GIRL', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'XERJOFF MORE THAN WORDS K20', 'price' => '5', 'manufacturer' => '66'],
        ['name' => 'SI ARMANI', 'price' => '0.5', 'manufacturer' => '66'],
        ['name' => 'BVLGARI TYGAR (2017)', 'price' => '3', 'manufacturer' => '66'],
        ['name' => 'PACO RABANNE ULTRAVIOLET', 'price' => '1.2', 'manufacturer' => '66'],
        ['name' => 'ANTONIO BANDERAS GOLDEN SECRET', 'price' => '1.2', 'manufacturer' => '66'],
    ];

    public $qablar = [
        ['name' => '20 ml əmmanə', 'price' => '1.5'],
        ['name' => '23 ml xüsusi', 'price' => '0.85'],
        ['name' => '25 ml kvadrat', 'price' => '1.2'],
        ['name' => '17 ml qara xallı', 'price' => '1.6'],
        ['name' => '10 ml uzun sprey', 'price' => '0.75'],
        ['name' => '50 ml Jomolun qara', 'price' => '2.05'],
        ['name' => '50 ml Jomolun ağ', 'price' => '2.05'],
        ['name' => '30 ml Jomolun qara', 'price' => '1.8'],
        ['name' => '30 ml Jomolun ağ', 'price' => '1.8'],
        ['name' => '50 ml xallı ağ', 'price' => '1.2'],
        ['name' => '10 ml sarik', 'price' => '0.4'],
        ['name' => '30 ml armani private', 'price' => '1.8'],
        ['name' => '20 ml Jadore', 'price' => '0.75'],
        ['name' => '30 ml aventus', 'price' => '1.1'],
        ['name' => '50 ml xejof', 'price' => '2.2'],
        ['name' => '50 ml naxışlı ştamp', 'price' => '2.5'],
        ['name' => '10 ml sprey sadə', 'price' => '0.25'],
        ['name' => '6 ml sprey sadə', 'price' => '0.2'],
        ['name' => '10 ml sprey metal qapaq (6 ədədli dəst - 2.5 AZN)', 'price' => '0.42'],
        ['name' => '10 ml sprey metal uzun (6 ədədli dəst - 2.7 AZN)', 'price' => '0.45'],
        ['name' => '10 ml sprey qızılı uzun (6 ədəli dəst - 4.80 AZN)', 'price' => '0.8'],
        ['name' => '10 ml sprey sadə', 'price' => '0.15'],
        ['name' => '5 qr şarik şüşə', 'price' => '0.2'],
        ['name' => '6 ml sprey sadə', 'price' => '0.13'],
        ['name' => '6 ml şarik', 'price' => '0.25'],
        ['name' => '5 ml qələm', 'price' => '1.1'],
        ['name' => '10 ml mat', 'price' => '0.45'],
        ['name' => '140 qr arseal qab', 'price' => '2'],
        ['name' => '250 qr arseal qab (qızılı)', 'price' => '7'],
        ['name' => '250 qr arseal qab (pilləkan)', 'price' => '9'],
        ['name' => '250 qr arseal qab (qızılı yumru qapaq)', 'price' => '5.5'],
        ['name' => '3 ml şarik plasmas qutu', 'price' => '0.07'],
        ['name' => '5 ml şarik plasmas qutu', 'price' => '0.11'],
        ['name' => '2 ml şarik plasmas qutu', 'price' => '0.08'],
        ['name' => '50 ml qab sadə', 'price' => '1.5'],
        ['name' => '30 ml qab sadə', 'price' => '1.3'],
        ['name' => '20 ml qab sadə', 'price' => '0.8'],
        ['name' => '20 ml qab göbələk', 'price' => '0.8'],
        ['name' => '25 ml qab 8 künc', 'price' => '0.85'],
        ['name' => '30 ml qab Jomolun', 'price' => '1.2'],
        ['name' => '12 ml qab mistkal', 'price' => '0.65'],
        ['name' => '15 ml qab kvadrat', 'price' => '0.95'],
        ['name' => '15 ml qab sadə', 'price' => '0.7'],
        ['name' => '60 ml Armani prive', 'price' => '3.5'],
        ['name' => '30 ml Jomolun sadə', 'price' => '1.7'],
        ['name' => '30 ml chanel', 'price' => '1.2'],
        ['name' => '40 ml Hugo boss', 'price' => '1.2'],
        ['name' => '50 ml xrustal', 'price' => '2.5'],
        ['name' => 'ərəb qabı', 'price' => '1.6'],
        ['name' => '50 ml ərəb qabı', 'price' => '3.2'],
        ['name' => '30 ml ulduz', 'price' => '1.9'],
        ['name' => '27 Gucci Bambo', 'price' => '1.3'],
        ['name' => '50 ml rəngli', 'price' => '1.5'],
        ['name' => '30 ml qara', 'price' => '1.2'],
        ['name' => '50 ml qara', 'price' => '1.3'],
        ['name' => '30 ml Badi sea', 'price' => '1.9'],
        ['name' => '50 ml Badi sea', 'price' => '2.25'],
        ['name' => '30 ml Xerjof', 'price' => '2'],
        ['name' => '30 ml Kirke', 'price' => '2'],
        ['name' => '30 ml Nuran', 'price' => '1.6'],
        ['name' => '30 ml Dior Savash', 'price' => '1'],
        ['name' => '30 ml Armani sea', 'price' => '1.3'],
        ['name' => '30 ml Oval', 'price' => '1.5'],
        ['name' => '90 ml qızılı', 'price' => '3.5'],
        ['name' => '30 ml Montale', 'price' => '1.15'],
        ['name' => '50 ml Montale', 'price' => '1.3'],
        ['name' => '80 ml Montale', 'price' => '2.85'],
        ['name' => '30 ml Korolva', 'price' => '1.6'],
        ['name' => '50 ml qızılı oval', 'price' => '1.8'],
        ['name' => '30 ml xətli', 'price' => '1.4'],
        ['name' => '30 ml rəngli baş', 'price' => '1.2'],
        ['name' => '50 ml buzlu', 'price' => '1.8'],
        ['name' => '50 ml boncuk', 'price' => '1.4'],
        ['name' => '50 ml bomshell', 'price' => '1.4'],
        ['name' => '30 ml naxışlı', 'price' => '1.4'],
        ['name' => '50 ml Chanel', 'price' => '1.55'],
        ['name' => '50 ml VİP parfum', 'price' => '1.9'],
        ['name' => '60 ml Nurik', 'price' => '1.8'],
        ['name' => '40 ml Koja qapaq', 'price' => '1.2'],
        ['name' => '30 ml Burberry', 'price' => '0.98'],
        ['name' => '30 ml sadə kvadrat', 'price' => '1.2'],
        ['name' => '30 ml xrustal tac qapaq', 'price' => '3'],
        ['name' => '100 ml tom ford', 'price' => '3'],
        ['name' => '50 ml tom ford', 'price' => '1.5'],
        ['name' => '100 ml koja qapaq', 'price' => '5'],
        ['name' => '50 ml tom ford kvadrat', 'price' => '2.5'],
        ['name' => '130 ml sadə', 'price' => '1.74'],
        ['name' => '100 ml xrustal', 'price' => '2.5'],
        ['name' => '80 ml xrustal', 'price' => '4'],
        ['name' => '80 ml V forma', 'price' => '3.3'],
        ['name' => '35 ml aventus', 'price' => '1.2'],
        ['name' => '30 ml The bliss', 'price' => '3.3'],
        ['name' => 'Bəzəkli xüsusi qab', 'price' => '4'],
        ['name' => '60 ml nasos', 'price' => '5.1'],
        ['name' => '25 ml chanel gümüşü', 'price' => '1'],
        ['name' => '25 ml chanel qızılı', 'price' => '1.1'],
        ['name' => '30 ml pilləkan', 'price' => '1'],
        ['name' => '50 ml k42', 'price' => '0.75'],
        ['name' => '30 ml K65', 'price' => '0.65'],
        ['name' => '20 ml Floor', 'price' => '1.2'],
        ['name' => '30 ml floor', 'price' => '1.5'],
        ['name' => '30 ml stranger', 'price' => '1.5'],
        ['name' => '8 kunc', 'price' => '0.8'],
        ['name' => '30 ml oval şəffəf', 'price' => '1'],
        ['name' => '30 ml Aquadigio', 'price' => '0.9'],
        ['name' => '30 ml kvadrat güllü', 'price' => '1.4'],
        ['name' => '35 ml daraq', 'price' => '1'],
        ['name' => '30 ml invicture', 'price' => '0.9'],
        ['name' => '30 ml triana ştamp', 'price' => '1.6'],
        ['name' => '30 ml təkər', 'price' => '1'],
        ['name' => '12 ml mişka', 'price' => '0.9'],
        ['name' => '30 ml one million', 'price' => '1.5'],
        ['name' => '50 ml rəngli - 2', 'price' => '1.2'],
        ['name' => '50 ml rəngli xrustal', 'price' => '1.4'],
        ['name' => '50 ml uzun', 'price' => '1.2'],
        ['name' => '30 ml piramida', 'price' => '0.8'],
        ['name' => '80 ml naxışlı kvadrat', 'price' => '3.25'],
        ['name' => '100 ml naxışlı yumru', 'price' => '3.25'],
        ['name' => '100 ml güllü', 'price' => '3.5'],
        ['name' => '100 ml nurlan', 'price' => '3.15'],
        ['name' => '100 ml Shaik', 'price' => '3'],
        ['name' => '100 ml risunka', 'price' => '3.15'],
        ['name' => '50 ml ştamp qapaq', 'price' => '1.5'],
    ];


    public function insertParfums(EntityManagerInterface $em)
    {
        $tenant = $em->getReference(Tenant::class, 24); //24
        $subCatalog = $em->getReference(ProductCatalog::class, 96);//96
        $uom = $em->getReference(UnitOfMeasurement::class, 110);//110

        $batchSize = 20;
        $i = 1;

        foreach ($this->parfums as $parfum) {

            $manufacturer = $em->getReference(Contact::class, $parfum['manufacturer']);

            $product = new Product();
            $product->setTenant($tenant);
            $product->setName($parfum['name']);
            $product->setSalesPrice($parfum['price']);
            $product->setCatalog($subCatalog);
            $product->setUnitOfMeasurement($uom);
            $product->setManufacturer($manufacturer);
            $em->persist($product);
            $i++;
        }

        $em->flush(); //Persist objects that did not make up an entire batch
        $em->clear();
    }

    public function insertQablar(EntityManagerInterface $em)
    {
        $tenant = $em->getReference(Tenant::class, 24); //24
        $subCatalog = $em->getReference(ProductCatalog::class, 96);//74
        $uom = $em->getReference(UnitOfMeasurement::class, 107);//107
        $manufacturer = $em->getReference(Contact::class, 67);

        $batchSize = 20;
        $i = 1;

        foreach ($this->qablar as $parfum) {
            $product = new Product();
            $product->setTenant($tenant);
            $product->setName($parfum['name']);
            $product->setSalesPrice($parfum['price']);
            $product->setCatalog($subCatalog);
            $product->setUnitOfMeasurement($uom);
            $product->setManufacturer($manufacturer);
            $em->persist($product);

            $i++;
        }

        $em->flush(); //Persist objects that did not make up an entire batch
        $em->clear();
    }
}