<?php


namespace App\Helper\Timezone;


class Date
{
    public static function getModifiedDateTime($modify = 'now')
    {
        $datetime = new \DateTime();
        $datetime->setTimezone(new \DateTimeZone("UTC"));
        $datetime->modify($modify);

        return $datetime;
    }

    public static function convertStringToUTCDateTime(?string $dateTimeStr, $timeZone): ?\DateTime
    {
        if (!(is_string($timeZone) || $timeZone instanceof \DateTimeZone)) {
            throw new \InvalidArgumentException();
        }

        if ($dateTimeStr !== null && $dateTimeStr !== '') {
            try {
                if (empty($timeZone)) {
                    $timeZone = 'UTC';
                }

                if (is_string($timeZone)) {
                    $timeZone = new \DateTimeZone($timeZone);
                }

                $dateTime = new \DateTime($dateTimeStr, $timeZone);
                $dateTime->setTimezone(new \DateTimeZone('UTC'));

                return $dateTime;

            } catch (\Exception $e) {
                return null;
            }
        }

        return null;
    }

    /**
     * @param $dateTimeObject
     * @return null|string
     */
    public static function formatDateTimeToDate($dateTimeObject)
    {
        return is_null($dateTimeObject) ? null : $dateTimeObject->format('d-m-Y');
    }

    public static function getTimeZones()
    {
        $dateTimeZone = [
            'Pacific/Midway',
            'Pacific/Niue',
            'Pacific/Pago_Pago',
            'America/Adak',
            'Pacific/Honolulu',
            'Pacific/Johnston',
            'Pacific/Rarotonga',
            'Pacific/Tahiti',
            'Pacific/Marquesas',
            'America/Anchorage',
            'Pacific/Gambier',
            'America/Juneau',
            'America/Nome',
            'America/Sitka',
            'America/Yakutat',
            'America/Dawson',
            'America/Los_Angeles',
            'America/Metlakatla',
            'Pacific/Pitcairn',
            'America/Santa_Isabel',
            'America/Tijuana',
            'America/Vancouver',
            'America/Whitehorse',
            'America/Boise',
            'America/Cambridge_Bay',
            'America/Chihuahua',
            'America/Creston',
            'America/Dawson_Creek',
            'America/Denver',
            'America/Edmonton',
            'America/Hermosillo',
            'America/Inuvik',
            'America/Mazatlan',
            'America/Ojinaga',
            'America/Phoenix',
            'America/Shiprock',
            'America/Yellowknife',
            'America/Bahia_Banderas',
            'America/Belize',
            'America/North_Dakota/Beulah',
            'America/Cancun',
            'America/North_Dakota/Center',
            'America/Chicago',
            'America/Costa_Rica',
            'Pacific/Easter',
            'America/El_Salvador',
            'Pacific/Galapagos',
            'America/Guatemala',
            'America/IndianaKnox',
            'America/Managua',
            'America/Matamoros',
            'America/Menominee',
            'America/Merida',
            'America/Mexico_City',
            'America/Monterrey',
            'America/North_Dakota/New_Salem',
            'America/Rainy_River',
            'America/Rankin_Inlet',
            'America/Regina' ,
            'America/Resolute' ,
            'America/Swift_Current',
            'America/Tegucigalpa',
            'America/Indiana/Tell City',
            'America/Winnipeg',
            'America/Atikokan',
            'America/Bogota' ,
            'America/Cayman' ,
            'America/Detroit' ,
            'America/Grand_Turk',
            'America/Guayaquil',
            'America/Havana',
            'America/Indiana/Indianapolis',
            'America/Iqaluit',
            'America/Jamaica',
            'America/Lima',
            'America/Kentucky/Louisville',
            'America/Indiana/Marengo',
            'America/Kentucky/Monticello',
            'America/Montreal',
            'America/Nassau',
            'America/New_York',
            'America/Nipigon',
            'America/Panama',
            'America/Pangnirtung',
            'America/Indiana/Petersburg',
            'America/Port-au-Prince',
            'America/Thunder_Bay',
            'America/Toronto',
            'America/Indiana/Vevay',
            'America/Indiana/Vincennes',
            'America/Indiana/Winamac',
            'America/Caracas',
            'America/Anguilla',
            'America/Antigua',
            'America/Aruba',
            'America/Asuncion',
            'America/Barbados',
            'Atlantic/Bermuda',
            'America/Blanc-Sablon',
            'America/Boa_Vista',
            'America/Campo_Grande',
            'America/Cuiaba',
            'America/Curacao',
            'America/Dominica',
            'America/Eirunepe',
            'America/Glace_Bay',
            'America/Goose_Bay',
            'America/Grenada',
            'America/Guadeloupe',
            'America/Guyana',
            'America/Halifax',
            'America/Kralendijk',
            'America/La_Paz',
            'America/Lower_Princes',
            'America/Manaus',
            'America/Marigot',
            'America/Martinique',
            'America/Moncton',
            'America/Montserrat',
            'Antarctica/Palmer',
            'America/Port_of_Spain',
            'America/Porto_Velho',
            'America/Puerto_Rico',
            'America/Rio_Branco',
            'America/Santiago',
            'America/Santo_Domingo',
            'America/St_Barthelemy',
            'America/St_Kitts',
            'America/St_Lucia',
            'America/St_Thomas',
            'America/St_Vincent',
            'America/Thule',
            'America/Tortola',
            'America/St_Johns' ,
            'America/Araguaina' ,
            'America/Bahia',
            'America/Belem',
            'America/Argentina/Buenos_Aires',
            'America/Argentina/Catamarca',
            'America/Cayenne',
            'America/Argentina/Cordoba',
            'America/Fortaleza',
            'America/Godthab',
            'America/Argentina/Jujuy',
            'America/Argentina/La_Rioja',
            'America/Maceio',
            'America/Argentina/Mendoza',
            'America/Miquelon',
            'America/Montevideo',
            'America/Paramaribo',
            'America/Recife',
            'America/Argentina/Rio_Gallegos',
            'Antarctica/Rothera',
            'America/Argentina/Salta' ,
            'America/Argentina/San_Juan',
            'America/Argentina/San_Luis',
            'America/Santarem',
            'America/Sao_Paulo',
            'Atlantic/Stanley',
            'America/Argentina/Tucuman',
            'America/Argentina/Ushuaia',
            'America/Noronha' ,
            'Atlantic/South_Georgia',
            'Atlantic/Azores',
            'Atlantic/Cape_Verde',
            'America/Scoresbysund',
            'Africa/Abidjan',
            'Africa/Accra',
            'Africa/Bamako',
            'Africa/Banjul',
            'Africa/Bissau',
            'Atlantic/Canary',
            'Africa/Casablanca',
            'Africa/Conakry',
            'Africa/Dakar',
            'America/Danmarkshavn',
            'Europe/Dublin',
            'Africa/El_Aaiun',
            'Atlantic/Faroe' ,
            'Africa/Freetown' ,
            'Europe/Guernsey' ,
            'Europe/Isle_of_Man',
            'Europe/Jersey' ,
            'Europe/Lisbon' ,
            'Africa/Lome' ,
            'Europe/London' ,
            'Atlantic/Madeira' ,
            'Africa/Monrovia' ,
            'Africa/Nouakchott' ,
            'Africa/Ouagadougou' ,
            'Atlantic/Reykjavik' ,
            'Africa/Sao_Tome',
            'Atlantic/St_Helena',
            'UTC',
            'Africa/Algiers',
            'Europe/Amsterdam',
            'Europe/Andorra',
            'Africa/Bangui',
            'Europe/Belgrade',
            'Europe/Berlin',
            'Europe/Bratislava',
            'Africa/Brazzaville',
            'Europe/Brussels',
            'Europe/Budapest',
            'Europe/Busingen',
            'Africa/Ceuta',
            'Europe/Copenhagen',
            'Africa/Douala',
            'Europe/Gibraltar',
            'Africa/Kinshasa',
            'Africa/Lagos',
            'Africa/Libreville',
            'Europe/Ljubljana',
            'Arctic/Longyearbyen',
            'Africa/Luanda',
            'Europe/Luxembourg',
            'Europe/Madrid',
            'Africa/Malabo',
            'Europe/Malta',
            'Europe/Monaco',
            'Africa/Ndjamena',
            'Africa/Niamey',
            'Europe/Oslo',
            'Europe/Paris',
            'Europe/Podgorica' ,
            'Africa/Porto-o-Novo',
            'Europe/Prague' ,
            'Europe/Rome',
            'Europe/San_Marino',
            'Europe/Sarajevo' ,
            'Europe/Skopje' ,
            'Europe/Stockholm' ,
            'Europe/Tirane' ,
            'Africa/Tripoli' ,
            'Africa/Tunis' ,
            'Europe/Vaduz' ,
            'Europe/Vatican' ,
            'Europe/Vienna' ,
            'Europe/Warsaw' ,
            'Africa/Windhoek' ,
            'Europe/Zagreb',
            'Europe/Zurich',
            'Europe/Athens',
            'Asia/Beirut',
            'Africa/Blantyre',
            'Europe/Bucharest',
            'Africa/Bujumbura',
            'Africa/Cairo',
            'Europe/Chisinau',
            'Asia/Damascus',
            'Africa/Gaborone',
            'Asia/Gaza',
            'Africa/Harare',
            'Asia/Hebron',
            'Europe/Helsinki',
            'Europe/Istanbul',
            'Asia/Jerusalem',
            'Africa/Johannesburg',
            'Europe/Kiev',
            'Africa/Kigali',
            'Africa/Lubumbashi',
            'Africa/Lusaka',
            'Africa/Maputo',
            'Europe/Mariehamn',
            'Africa/Maseru',
            'Africa/Mbabane',
            'Asia/Nicosia',
            'Europe/Riga',
            'Europe/Simferopol',
            'Europe/Sofia',
            'Europe/Tallinn',
            'Europe/Uzhgorod',
            'Europe/Vilnius' ,
            'Europe/Zaporozhye',
            'Africa/Addis_Ababa',
            'Asia/Aden',
            'Asia/Amman',
            'Indian/Antananarivo',
            'Africa/Asmara',
            'Asia/Baghdad',
            'Asia/Bahrain',
            'Indian/Comoro',
            'Africa/Dar_es_Salaam',
            'Africa/Djibouti',
            'Africa/Juba',
            'Europe/Kaliningrad',
            'Africa/Kampala',
            'Africa/Khartoum',
            'Asia/Kuwait',
            'Indian/Mayotte',
            'Europe/Minsk',
            'Africa/Mogadishu',
            'Africa/Nairobi',
            'Asia/Qatar',
            'Asia/Riyadh',
            'Antarctica/Syowa',
            'Asia/Tehran',
            'Asia/Baku',
            'Asia/Dubai',
            'Indian/Mahe',
            'Indian/Mauritius',
            'Europe/Moscow',
            'Asia/Muscat',
            'Indian/Reunion',
            'Europe/Samara',
            'Asia/Tbilisi',
            'Europe/Volgograd',
            'Asia/Yerevan',
            'Asia/Kabul',
            'Asia/Aqtau',
            'Asia/Aqtobe',
            'Asia/Ashgabat',
            'Asia/Dushanbe',
            'Asia/Karachi',
            'Indian/Kerguelen',
            'Indian/Maldives',
            'Antarctica/Mawson',
            'Asia/Oral',
            'Asia/Samarkand',
            'Asia/Tashkent',
            'Asia/Colombo',
            'Asia/Kolkata',
            'Asia/Kathmandu',
            'Asia/Almaty',
            'Asia/Bishkek',
            'Indian/Chagos',
            'Asia/Dhaka',
            'Asia/Qyzylorda',
            'Asia/Thimphu',
            'Antarctica/Vostok',
            'Asia/Yekaterinburg',
            'Indian/Cocos',
            'Asia/Rangoon',
            'Asia/Bangkok',
            'Indian/Christmas',
            'Antarctica/Davis',
            'Asia/Ho_Chi_Minh',
            'Asia/Hovd',
            'Asia/Jakarta',
            'Asia/Novokuznetsk',
            'Asia/Novosibirsk',
            'Asia/Omsk',
            'Asia/Phnom_Penh',
            'Asia/Pontianak',
            'Asia/Vientiane',
            'Asia/Brunei',
            'Antarctica/Casey',
            'Asia/Choibalsan',
            'Asia/Chongqing',
            'Asia/Harbin',
            'Asia/Hong_Kong',
            'Asia/Kashgar',
            'Asia/Krasnoyarsk',
            'Asia/Kuala_Lumpur',
            'Asia/Kuching',
            'Asia/Macau',
            'Asia/Makassar',
            'Asia/Manila',
            'Australia/Perth',
            'Asia/Shanghai',
            'Asia/Singapore',
            'Asia/Taipei',
            'Asia/Ulaanbaatar',
            'Asia/Urumqi',
            'Australia/Eucla',
            'Asia/Dili',
            'Asia/Irkutsk',
            'Asia/Jayapura',
            'Pacific/Palau',
            'Asia/Pyongyang',
            'Asia/Seoul',
            'Asia/Tokyo',
            'Australia/Adelaide',
            'Australia/Broken_Hill',
            'Australia/Darwin',
            'Australia/Brisbane',
            'Pacific/Chuuk',
            'Australia/Currie',
            'Antarctica/DumontDUrville',
            'Pacific/Guam',
            'Australia/Hobart',
            'Asia/Khandyga',
            'Australia/Lindeman',
            'Australia/Melbourne',
            'Pacific/Port_Moresby',
            'Pacific/Saipan',
            'Australia/Sydney',
            'Asia/Yakutsk',
            'Australia/Lord_Howe',
            'Pacific/Efate',
            'Pacific/Guadalcanal',
            'Pacific/Kosrae',
            'Antarctica/Macquarie',
            'Pacific/Noumea',
            'Pacific/Pohnpei',
            'Asia/Sakhalin',
            'Asia/Ust Ust-Nera',
            'Asia/Vladivostok',
            'Pacific/Norfolk',
            'Asia/Anadyr',
            'Pacific/Auckland',
            'Pacific/Fiji',
            'Pacific/Funafuti',
            'Asia/Kamchatka',
            'Pacific/Kwajalein',
            'Asia/Magadan',
            'Pacific/Majuro',
            'Antarctica/McMurdo',
            'Pacific/Nauru',
            'Antarctica/South_Pole',
            'Pacific/Tarawa',
            'Pacific/Wake',
            'Pacific/Wallis',
            'Pacific/Chatham',
            'Pacific/Apia',
            'Pacific/Enderbury',
            'Pacific/Fakaofo',
            'Pacific/Tongatapu',
            'Pacific/Kiritimati',
        ];

        return $dateTimeZone;
    }
}
